"""
StockHomeTH - Comprehensive Thai Stock Catalog Builder (SET & mai)
Generates 500+ Thai stocks with accurate company names, sectors, industries,
and saves to server/data/thai_stocks.json.
"""

import os
import json
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_FILE = os.path.join(BASE_DIR, "server", "data", "thai_stocks.json")

# Comprehensive List of Thai SET & mai Listed Companies
THAI_COMPANIES = [
    # ─── 1. AGRO & FOOD INDUSTRY (เกษตรและอุตสาหกรรมอาหาร) ───
    ("CPF",    "Charoen Pokphand Foods PCL",             "Food & Beverage",            "Agro & Food"),
    ("TU",     "Thai Union Group PCL",                   "Food & Beverage",            "Agro & Food"),
    ("CBG",    "Carabao Group PCL",                      "Food & Beverage",            "Agro & Food"),
    ("OSP",    "Osotspa Public Company Limited",         "Food & Beverage",            "Agro & Food"),
    ("ICHI",   "Ichitan Group PCL",                      "Food & Beverage",            "Agro & Food"),
    ("SAPPE",  "Sappe Public Company Limited",           "Food & Beverage",            "Agro & Food"),
    ("TKN",    "Taokaenoi Food & Marketing PCL",         "Food & Beverage",            "Agro & Food"),
    ("BTG",    "Betagro Public Company Limited",         "Food & Beverage",            "Agro & Food"),
    ("GFPT",   "GFPT Public Company Limited",            "Food & Beverage",            "Agro & Food"),
    ("ITC",    "i-Tail Corporation PCL",                 "Food & Beverage",            "Agro & Food"),
    ("XO",     "Exotic Food PCL",                        "Food & Beverage",            "Agro & Food"),
    ("COCOCO", "Thai Coconut Public Company Limited",    "Food & Beverage",            "Agro & Food"),
    ("PLUS",   "Royal Plus Public Company Limited",      "Food & Beverage",            "Agro & Food"),
    ("MALEE",  "Malee Group Public Company Limited",     "Food & Beverage",            "Agro & Food"),
    ("TIPCO",  "Tipco Foods Public Company Limited",     "Food & Beverage",            "Agro & Food"),
    ("APURE",  "AgriPure Holdings PCL",                  "Food & Beverage",            "Agro & Food"),
    ("ASIAN",  "Asian Alliance International PCL",       "Food & Beverage",            "Agro & Food"),
    ("KSL",    "Khon Kaen Sugar Industry PCL",           "Agribusiness & Sugar",       "Agro & Food"),
    ("KBS",    "Khonburi Sugar Public Company Limited",  "Agribusiness & Sugar",       "Agro & Food"),
    ("KTIS",   "Kaset Thai International Sugar Corp",    "Agribusiness & Sugar",       "Agro & Food"),
    ("BRR",    "Buriram Sugar Public Company Limited",   "Agribusiness & Sugar",       "Agro & Food"),
    ("TWPC",   "Thai Wah Public Company Limited",        "Agribusiness & Starch",      "Agro & Food"),
    ("TVO",    "Thai Vegetable Oil PCL",                 "Agribusiness & Oil",         "Agro & Food"),
    ("SUN",    "Sunsweet Public Company Limited",        "Food & Beverage",            "Agro & Food"),
    ("TFG",    "Thai Foods Group PCL",                   "Food & Beverage",            "Agro & Food"),
    ("RBF",    "R&B Food Supply PCL",                    "Food & Beverage",            "Agro & Food"),
    ("NSL",    "NSL Foods Public Company Limited",       "Food & Beverage",            "Agro & Food"),
    ("CH",     "Charoen Industry PCL",                   "Food & Beverage",            "Agro & Food"),
    ("TTEET",  "Thai Eastern Group Holdings PCL",        "Agribusiness & Rubber",      "Agro & Food"),
    ("STA",    "Sri Trang Agro-Industry PCL",            "Agribusiness & Rubber",      "Agro & Food"),
    ("NER",    "North East Rubber PCL",                  "Agribusiness & Rubber",      "Agro & Food"),
    ("TRUBB",  "Thai Rubber Latex Group PCL",            "Agribusiness & Rubber",      "Agro & Food"),
    ("CM",     "Chiangmai Frozen Foods PCL",             "Food & Beverage",            "Agro & Food"),

    # ─── 2. CONSUMER PRODUCTS (สินค้าอุปโภคบริโภค) ───
    ("KAMART", "Karmarts Public Company Limited",        "Commerce & Retail",          "Consumer Products"),
    ("MOSHI",  "Moshi Moshi Retail Corp PCL",            "Commerce & Retail",          "Consumer Products"),
    ("BEAUTY", "Beauty Community PCL",                   "Commerce & Retail",          "Consumer Products"),
    ("SABINA", "Sabina Public Company Limited",          "Fashion & Apparel",          "Consumer Products"),
    ("TACC",   "T.A.C. Consumer PCL",                    "Consumer Goods",             "Consumer Products"),
    ("TOG",    "Thai Optical Group PCL",                 "Personal Products",          "Consumer Products"),
    ("WACOAL", "Thai Wacoal Public Company Limited",     "Fashion & Apparel",          "Consumer Products"),
    ("OCC",    "O.C.C. Public Company Limited",          "Personal Products",          "Consumer Products"),
    ("PG",     "People's Garment PCL",                   "Fashion & Apparel",          "Consumer Products"),
    ("SAUCE",  "Thai Theparos PCL",                      "Food & Consumer",            "Consumer Products"),
    ("PB",     "President Bakery PCL",                   "Food & Consumer",            "Consumer Products"),
    ("TF",     "Thai President Foods PCL",               "Food & Consumer",            "Consumer Products"),

    # ─── 3. FINANCIALS & BANKING (ธุรกิจการเงินและธนาคาร) ───
    ("KBANK",  "Kasikornbank Public Company Limited",    "Banking & Financials",      "Financials"),
    ("SCB",    "SCB X Public Company Limited",           "Banking & Financials",      "Financials"),
    ("BBL",    "Bangkok Bank Public Company Limited",    "Banking & Financials",      "Financials"),
    ("KTB",    "Krungthai Bank Public Company Limited",  "Banking & Financials",      "Financials"),
    ("TTB",    "TMBThanachart Bank PCL",                 "Banking & Financials",      "Financials"),
    ("TISCO",  "TISCO Financial Group PCL",              "Banking & Financials",      "Financials"),
    ("TCAP",   "Thanachart Capital PCL",                 "Banking & Financials",      "Financials"),
    ("KKP",    "Kiatnakin Phatra Bank PCL",              "Banking & Financials",      "Financials"),
    ("BAY",    "Bank of Ayudhya PCL (Krungsri)",         "Banking & Financials",      "Financials"),
    ("CIMBT",  "CIMB Thai Bank PCL",                     "Banking & Financials",      "Financials"),
    ("LHFG",   "LH Financial Group PCL",                 "Banking & Financials",      "Financials"),
    ("KTC",    "Krungthai Card PCL",                     "Banking & Financials",      "Financials"),
    ("SAWAD",  "Srisawad Corporation PCL",               "Banking & Financials",      "Financials"),
    ("MTC",    "Muangthai Capital PCL",                  "Banking & Financials",      "Financials"),
    ("TIDLOR", "Ngern Tid Lor Public Co., Ltd.",         "Banking & Financials",      "Financials"),
    ("BAM",    "Bangkok Commercial Asset Management",    "Banking & Financials",      "Financials"),
    ("THANI",  "Ratchthani Leasing PCL",                 "Banking & Financials",      "Financials"),
    ("JMT",    "JMT Network Services PCL",               "Banking & Financials",      "Financials"),
    ("JMART",  "Jay Mart Public Company Limited",        "Banking & Financials",      "Financials"),
    ("TLI",    "Thai Life Insurance PCL",                "Banking & Financials",      "Financials"),
    ("AEONTS", "AEON Thana Sinsap (Thailand) PCL",       "Banking & Financials",      "Financials"),
    ("SAK",    "Saksiam Leasing PCL",                    "Banking & Financials",      "Financials"),
    ("HENG",   "Heng Leasing and Capital PCL",           "Banking & Financials",      "Financials"),
    ("MICRO",  "Micro Leasing PCL",                      "Banking & Financials",      "Financials"),
    ("NCAP",   "Next Capital Public Company Limited",    "Banking & Financials",      "Financials"),
    ("CHAYO",  "Chayo Group Public Company Limited",     "Banking & Financials",      "Financials"),
    ("ECL",    "Eastern Commercial Leasing PCL",         "Banking & Financials",      "Financials"),
    ("ASK",    "Asia Sermkij Leasing PCL",               "Banking & Financials",      "Financials"),
    ("IFS",    "IFS Capital (Thailand) PCL",             "Banking & Financials",      "Financials"),
    ("S11",    "S11 Group Public Company Limited",       "Banking & Financials",      "Financials"),
    ("BYD",    "Beyond Securities PCL",                  "Banking & Financials",      "Financials"),
    ("KGI",    "KGI Securities (Thailand) PCL",          "Banking & Financials",      "Financials"),
    ("FSS",    "Finansia Syrus Securities PCL",          "Banking & Financials",      "Financials"),
    ("ASP",    "Asia Plus Group Holdings PCL",           "Banking & Financials",      "Financials"),
    ("TIPH",   "Dhipaya Group Holdings PCL",             "Banking & Financials",      "Financials"),
    ("BLA",    "Bangkok Life Assurance PCL",             "Banking & Financials",      "Financials"),
    ("BKI",    "Bangkok Insurance Public Co., Ltd.",     "Banking & Financials",      "Financials"),
    ("THREL",  "Thaire Life Assurance PCL",              "Banking & Financials",      "Financials"),

    # ─── 4. INDUSTRIALS & MATERIALS (สินค้าอุตสาหกรรมและเคมีภัณฑ์) ───
    ("DELTA",  "Delta Electronics (Thailand) PCL",       "Electronics & Tech",        "Industrials"),
    ("HANA",   "Hana Microelectronics PCL",              "Electronics & Tech",        "Industrials"),
    ("KCE",    "KCE Electronics Public Company Limited", "Electronics & Tech",        "Industrials"),
    ("CCET",   "Cal-Comp Electronics (Thailand) PCL",    "Electronics & Tech",        "Industrials"),
    ("SVI",    "SVI Public Company Limited",             "Electronics & Tech",        "Industrials"),
    ("FORTH",  "Forth Corporation PCL",                  "Electronics & Tech",        "Industrials"),
    ("TEAM",   "Team Precision Public Company Limited",  "Electronics & Tech",        "Industrials"),
    ("SMT",    "Stars Microelectronics (Thailand) PCL",  "Electronics & Tech",        "Industrials"),
    ("SNC",    "SNC Former Public Company Limited",      "Industrial Materials",      "Industrials"),
    ("IVL",    "Indorama Ventures PCL",                  "Petrochemicals & Chemicals", "Industrials"),
    ("PTTGC",  "PTT Global Chemical PCL",                "Petrochemicals & Chemicals", "Industrials"),
    ("STGT",   "Sri Trang Gloves (Thailand) PCL",        "Healthcare & Rubber",       "Industrials"),
    ("TPIPL",  "TPI Polene Public Company Limited",      "Industrial Materials",      "Industrials"),
    ("SCGP",   "SCG Packaging PCL",                      "Packaging & Paper",         "Industrials"),
    ("BGC",    "BG Container Glass PCL",                 "Packaging & Glass",         "Industrials"),
    ("AJ",     "A.J. Plast Public Company Limited",      "Packaging Materials",       "Industrials"),
    ("PTL",    "Polyplex (Thailand) Public Co., Ltd.",   "Packaging Materials",       "Industrials"),
    ("UTP",    "United Paper Public Company Limited",    "Packaging & Paper",         "Industrials"),
    ("EP",     "Eastern Power Group PCL",                "Industrial & Power",        "Industrials"),
    ("POLY",   "Plantation Watch Poly PCL",              "Industrial Plastics",       "Industrials"),
    ("PIMO",   "Pioneer Motor Public Company Limited",   "Industrial Machinery",      "Industrials"),

    # ─── 5. PROPERTY & CONSTRUCTION (อสังหาริมทรัพย์และก่อสร้าง) ───
    ("CPN",    "Central Pattana PCL",                    "Property & Real Estate",     "Property & Construction"),
    ("LH",     "Land and Houses PCL",                    "Property & Real Estate",     "Property & Construction"),
    ("AP",     "AP (Thailand) Public Company Limited",   "Property & Real Estate",     "Property & Construction"),
    ("SIRI",   "Sansiri Public Company Limited",         "Property & Real Estate",     "Property & Construction"),
    ("SPALI",  "Supalai Public Company Limited",         "Property & Real Estate",     "Property & Construction"),
    ("WHA",    "WHA Corporation PCL",                    "Property & Real Estate",     "Property & Construction"),
    ("AMATA",  "Amata Corporation PCL",                  "Property & Real Estate",     "Property & Construction"),
    ("AWC",    "Asset World Corp PCL",                   "Property & Real Estate",     "Property & Construction"),
    ("QH",     "Quality Houses PCL",                     "Property & Real Estate",     "Property & Construction"),
    ("ORI",    "Origin Property PCL",                    "Property & Real Estate",     "Property & Construction"),
    ("BRI",    "Britania Public Company Limited",        "Property & Real Estate",     "Property & Construction"),
    ("NOBLE",  "Noble Development PCL",                  "Property & Real Estate",     "Property & Construction"),
    ("ANAN",   "Ananda Development PCL",                 "Property & Real Estate",     "Property & Construction"),
    ("SC",     "SC Asset Corporation PCL",               "Property & Real Estate",     "Property & Construction"),
    ("SENA",   "Sena Development PCL",                   "Property & Real Estate",     "Property & Construction"),
    ("LALIN",  "Lalin Property PCL",                     "Property & Real Estate",     "Property & Construction"),
    ("ASW",    "AssetWise Public Company Limited",       "Property & Real Estate",     "Property & Construction"),
    ("PEACE",  "Peace and Living PCL",                   "Property & Real Estate",     "Property & Construction"),
    ("PRIN",   "Prinsiri Public Company Limited",        "Property & Real Estate",     "Property & Construction"),
    ("RICHY",  "Richy Place 2002 PCL",                   "Property & Real Estate",     "Property & Construction"),
    ("CHEWA",  "Chewathai Public Company Limited",       "Property & Real Estate",     "Property & Construction"),
    ("SAMCO",  "Siam Agro-City PCL",                     "Property & Real Estate",     "Property & Construction"),
    ("NCH",    "N.C. Housing Public Company Limited",    "Property & Real Estate",     "Property & Construction"),
    ("ESTAR",  "Eastern Star Real Estate PCL",           "Property & Real Estate",     "Property & Construction"),
    ("PIN",    "Pinthong Industrial Park PCL",           "Property & Real Estate",     "Property & Construction"),
    ("ROJNA",  "Rojana Industrial Park PCL",             "Property & Real Estate",     "Property & Construction"),
    ("SCC",    "The Siam Cement PCL",                    "Construction & Materials",  "Property & Construction"),
    ("SCCC",   "Siam City Cement PCL",                   "Construction & Materials",  "Property & Construction"),
    ("TASCO",  "Tipco Asphalt PCL",                      "Construction & Materials",  "Property & Construction"),
    ("DCC",    "Dynasty Ceramic Public Company Limited", "Construction & Materials",  "Property & Construction"),
    ("COTTO",  "SCG Decor Public Company Limited",       "Construction & Materials",  "Property & Construction"),
    ("TOA",    "TOA Paint (Thailand) PCL",               "Construction & Materials",  "Property & Construction"),
    ("CK",     "CH. Karnchang PCL",                      "Construction & Materials",  "Property & Construction"),
    ("STEC",   "Sino-Thai Engineering & Construction",   "Construction & Materials",  "Property & Construction"),
    ("ITD",    "Italian-Thai Development PCL",           "Construction & Materials",  "Property & Construction"),
    ("UNIQ",   "Unique Engineering and Construction PCL","Construction & Materials",  "Property & Construction"),
    ("SEAFCO", "Seafco Public Company Limited",          "Construction & Materials",  "Property & Construction"),
    ("PYLON",  "Pylon Public Company Limited",           "Construction & Materials",  "Property & Construction"),
    ("TEAMG",  "TEAM Consulting Engineering and Mgmt",   "Construction & Materials",  "Property & Construction"),
    ("SYNTEC", "Syntec Construction PCL",                "Construction & Materials",  "Property & Construction"),
    ("NWR",    "Nawarat Patanakarn PCL",                 "Construction & Materials",  "Property & Construction"),
    ("TRC",    "TRC Construction Public Company Limited","Construction & Materials",  "Property & Construction"),
    ("PLE",    "Power Line Engineering PCL",             "Construction & Materials",  "Property & Construction"),

    # ─── 6. RESOURCES & ENERGY (พลังงานและทรัพยากร) ───
    ("PTT",    "PTT Public Company Limited",             "Energy & Utilities",         "Resources"),
    ("PTTEP",  "PTT Exploration and Production PCL",     "Energy & Utilities",         "Resources"),
    ("TOP",    "Thai Oil Public Company Limited",        "Energy & Utilities",         "Resources"),
    ("GULF",   "Gulf Energy Development PCL",            "Energy & Utilities",         "Resources"),
    ("GPSC",   "Global Power Synergy PCL",               "Energy & Utilities",         "Resources"),
    ("BGRIM",  "B.Grimm Power PCL",                     "Energy & Utilities",         "Resources"),
    ("OR",     "PTT Oil and Retail Business PCL",        "Energy & Utilities",         "Resources"),
    ("EA",     "Energy Absolute Public Company Limited", "Energy & Utilities",         "Resources"),
    ("BANPU",  "Banpu Public Company Limited",           "Energy & Utilities",         "Resources"),
    ("RATCH",  "RATCH Group Public Company Limited",     "Energy & Utilities",         "Resources"),
    ("EGCO",   "Electricity Generating PCL",             "Energy & Utilities",         "Resources"),
    ("IRPC",   "IRPC Public Company Limited",            "Energy & Utilities",         "Resources"),
    ("BCP",    "Bangchak Corporation PCL",               "Energy & Utilities",         "Resources"),
    ("BCPG",   "BCPG Public Company Limited",            "Energy & Utilities",         "Resources"),
    ("SPRC",   "Star Petroleum Refining PCL",            "Energy & Utilities",         "Resources"),
    ("ACE",    "Absolute Clean Energy PCL",              "Energy & Utilities",         "Resources"),
    ("CKP",    "CK Power Public Company Limited",        "Energy & Utilities",         "Resources"),
    ("TTW",    "TTW Public Company Limited",             "Energy & Utilities",         "Resources"),
    ("WHAUP",  "WHA Utilities and Power PCL",            "Energy & Utilities",         "Resources"),
    ("TPIPP",  "TPI Polene Power PCL",                   "Energy & Utilities",         "Resources"),
    ("PTG",    "PTG Energy Public Company Limited",      "Energy & Utilities",         "Resources"),
    ("BBGI",   "BBGI Public Company Limited",            "Energy & Utilities",         "Resources"),
    ("SSP",    "Sermsang Power Corporation PCL",         "Energy & Utilities",         "Resources"),
    ("GUNKUL", "Gunkul Engineering PCL",                 "Energy & Utilities",         "Resources"),
    ("DEMCO",  "Demco Public Company Limited",           "Energy & Utilities",         "Resources"),
    ("BPP",    "Banpu Power Public Company Limited",     "Energy & Utilities",         "Resources"),
    ("TPCH",   "TPC Power Holding PCL",                  "Energy & Utilities",         "Resources"),
    ("PSTC",   "Power Solution Technology PCL",          "Energy & Utilities",         "Resources"),
    ("SUPER",  "Super Energy Corporation PCL",           "Energy & Utilities",         "Resources"),
    ("PRIME",  "Prime Road Power PCL",                   "Energy & Utilities",         "Resources"),
    ("ETC",    "Earth Tech Environment PCL",             "Energy & Utilities",         "Resources"),
    ("7UP",    "Seven Utilities and Power PCL",          "Energy & Utilities",         "Resources"),
    ("EASTW",  "Eastern Water Resources Development",    "Energy & Utilities",         "Resources"),
    ("SUSCO",  "Susco Public Company Limited",           "Energy & Utilities",         "Resources"),
    ("BAFS",   "Bangkok Aviation Fuel Services PCL",     "Energy & Utilities",         "Resources"),

    # ─── 7. SERVICES (การบริการ ค้าปลีก โรงพยาบาล ขนส่ง โรงแรม) ───
    ("CPALL",  "CP ALL Public Company Limited",          "Commerce & Retail",          "Services"),
    ("CPAXT",  "CP Axtra Public Company Limited",        "Commerce & Retail",          "Services"),
    ("CRC",    "Central Retail Corporation PCL",         "Commerce & Retail",          "Services"),
    ("HMPRO",  "Home Product Center PCL",                "Commerce & Retail",          "Services"),
    ("COM7",   "COM7 Public Company Limited",            "Commerce & Retail",          "Services"),
    ("BJC",    "Berli Jucker Public Company Limited",    "Commerce & Retail",          "Services"),
    ("GLOBAL", "Siam Global House PCL",                  "Commerce & Retail",          "Services"),
    ("DOHOME", "Dohome Public Company Limited",          "Commerce & Retail",          "Services"),
    ("MEGA",   "Mega Lifesciences PCL",                  "Commerce & Retail",          "Services"),
    ("AURA",   "Aura Gold Public Company Limited",       "Commerce & Retail",          "Services"),
    ("ILM",    "Index Living Mall PCL",                  "Commerce & Retail",          "Services"),
    ("MC",     "MC Group Public Company Limited",        "Commerce & Retail",          "Services"),
    ("RS",     "RS Public Company Limited",              "Media & Commerce",           "Services"),
    ("WORK",   "Workpoint Entertainment PCL",            "Media & Entertainment",      "Services"),
    ("VGI",    "VGI Public Company Limited",             "Media & Advertising",        "Services"),
    ("PLANB",  "Plan B Media PCL",                       "Media & Advertising",        "Services"),
    ("MAJOR",  "Major Cineplex Group PCL",               "Media & Entertainment",      "Services"),
    ("ONEE",   "The One Enterprise PCL",                 "Media & Entertainment",      "Services"),
    ("BEC",    "BEC World Public Company Limited (Ch3)", "Media & Entertainment",      "Services"),
    ("GRAMMY", "GMM Grammy Public Company Limited",      "Media & Entertainment",      "Services"),
    ("MONO",   "Mono Next Public Company Limited",       "Media & Entertainment",      "Services"),
    ("MCOT",   "MCOT Public Company Limited",            "Media & Entertainment",      "Services"),
    ("BDMS",   "Bangkok Dusit Medical Services PCL",     "Healthcare & Hospitals",     "Services"),
    ("BH",     "Bumrungrad Hospital PCL",                "Healthcare & Hospitals",     "Services"),
    ("BCH",    "Bangkok Chain Hospital PCL",             "Healthcare & Hospitals",     "Services"),
    ("CHG",    "Chularat Hospital PCL",                  "Healthcare & Hospitals",     "Services"),
    ("PR9",    "Praram 9 Hospital PCL",                  "Healthcare & Hospitals",     "Services"),
    ("MASTER", "Master Style Public Company Limited",    "Healthcare & Hospitals",     "Services"),
    ("KLINIQ", "The Klinique Medical Clinic PCL",        "Healthcare & Hospitals",     "Services"),
    ("PRINC",  "Principal Capital PCL",                  "Healthcare & Hospitals",     "Services"),
    ("THG",    "Thonburi Healthcare Group PCL",          "Healthcare & Hospitals",     "Services"),
    ("RJH",    "Rajthanee Hospital PCL",                 "Healthcare & Hospitals",     "Services"),
    ("EKH",    "Ekachai Medical Care PCL",               "Healthcare & Hospitals",     "Services"),
    ("VIBHA",  "Vibhavadi Medical Center PCL",           "Healthcare & Hospitals",     "Services"),
    ("CMR",    "Chiangmai Ram Medical Company",          "Healthcare & Hospitals",     "Services"),
    ("RAM",    "Ramkhamhaeng Hospital PCL",              "Healthcare & Hospitals",     "Services"),
    ("AOT",    "Airports of Thailand PCL",               "Transportation & Logistics", "Services"),
    ("BTS",    "BTS Group Holdings PCL",                 "Transportation & Logistics", "Services"),
    ("BEM",    "Bangkok Expressway and Metro PCL",       "Transportation & Logistics", "Services"),
    ("AAV",    "Asia Aviation Public Company Limited",   "Transportation & Logistics", "Services"),
    ("BA",     "Bangkok Airways PCL",                    "Transportation & Logistics", "Services"),
    ("SAV",    "Samart Aviation Solutions PCL",         "Transportation & Logistics", "Services"),
    ("PRM",    "Prima Marine Public Company Limited",    "Transportation & Logistics", "Services"),
    ("PSL",    "Precious Shipping PCL",                  "Transportation & Logistics", "Services"),
    ("RCL",    "Regional Container Lines PCL",           "Transportation & Logistics", "Services"),
    ("SJWD",   "SCGJWD Logistics PCL",                   "Transportation & Logistics", "Services"),
    ("III",    "Triple i Logistics PCL",                 "Transportation & Logistics", "Services"),
    ("WICE",   "WICE Logistics Public Company Limited",  "Transportation & Logistics", "Services"),
    ("NYT",    "Nam Seng Insurance & Logistics",         "Transportation & Logistics", "Services"),
    ("KEX",    "KEX Express (Thailand) PCL",             "Transportation & Logistics", "Services"),
    ("MENA",   "Mena Transport Public Company Limited",  "Transportation & Logistics", "Services"),
    ("PORT",   "Sahathai Terminal PCL",                  "Transportation & Logistics", "Services"),
    ("MINT",   "Minor International PCL",                "Tourism & Hospitality",      "Services"),
    ("CENTEL", "Central Plaza Hotel PCL",                "Tourism & Hospitality",      "Services"),
    ("ERW",    "The Erawan Group PCL",                   "Tourism & Hospitality",      "Services"),
    ("SHR",    "S Hotels and Resorts PCL",               "Tourism & Hospitality",      "Services"),
    ("VRANDA", "Veranda Resort PCL",                     "Tourism & Hospitality",      "Services"),
    ("DUSIT",  "Dusit Thani Public Company Limited",     "Tourism & Hospitality",      "Services"),
    ("GRAND",  "Grand Asset Hotels and Property",        "Tourism & Hospitality",      "Services"),
    ("ASIA",   "Asia Hotel Public Company Limited",      "Tourism & Hospitality",      "Services"),
    ("SISB",   "SISB Public Company Limited (School)",   "Education & Services",       "Services"),

    # ─── 8. TECHNOLOGY & DIGITAL (เทคโนโลยีและการสื่อสาร) ───
    ("ADVANC", "Advanced Info Service PCL (AIS)",        "Telecom & Digital",          "Technology"),
    ("TRUE",   "True Corporation PCL",                   "Telecom & Digital",          "Technology"),
    ("INTUCH", "Intouch Holdings PCL",                   "Telecom & Digital",          "Technology"),
    ("JAS",    "Jasmine International PCL",              "Telecom & Digital",          "Technology"),
    ("SKY",    "SKY ICT Public Company Limited",         "Technology & Software",      "Technology"),
    ("DITTO",  "Ditto (Thailand) Public Co., Ltd.",      "Technology & Software",      "Technology"),
    ("BE8",    "Beryl 8 Plus Public Company Limited",    "Technology Consulting",      "Technology"),
    ("BBIK",   "Bluebik Group Public Company Limited",   "Technology Consulting",      "Technology"),
    ("HUMAN",  "Humanica Public Company Limited",        "Technology & Software",      "Technology"),
    ("NETBAY", "Netbay Public Company Limited",          "Digital Technology",         "Technology"),
    ("INSET",  "Infraset Public Company Limited",        "Data Center & Telecom",      "Technology"),
    ("ITEL",   "Interlink Telecom PCL",                  "Data Center & Telecom",      "Technology"),
    ("ILINK",  "Interlink Communication PCL",            "Telecom & Engineering",      "Technology"),
    ("AIT",    "Advanced Information Technology PCL",    "IT Infrastructure",          "Technology"),
    ("SIS",    "SiS Distribution (Thailand) PCL",        "IT Distribution",            "Technology"),
    ("SYNEX",  "Synnex (Thailand) PCL",                  "IT Distribution",            "Technology"),
    ("SPVI",   "S P V I Public Company Limited",         "IT Retail",                  "Technology"),
    ("CPW",    "Copperwired Public Company Limited",     "IT Retail",                  "Technology"),
    ("JTS",    "Jasmine Technology Solution PCL",        "Cloud & AI Tech",            "Technology"),
    ("SAMART", "Samart Corporation PCL",                 "Technology Solutions",       "Technology"),
    ("SAMTEL", "Samart Telcoms PCL",                     "Technology Solutions",       "Technology"),
    ("IIG",    "I&I Group Public Company Limited",       "Technology Consulting",      "Technology"),
    ("PROEN",  "Proen Corp Public Company Limited",      "Data Center & Cloud",        "Technology"),
    ("SECURE", "nForce Secure Public Company Limited",   "Cybersecurity",              "Technology"),
    ("TBN",    "TBN Corporation PCL",                    "Low-Code Software Tech",     "Technology"),
    ("READY",  "ReadyPlanet Public Company Limited",     "Digital Marketing Platform", "Technology"),
    ("COMAN",  "Comanche International PCL",             "Software & Tech",            "Technology"),
    ("YGG",    "Yggdrazil Group PCL",                    "VFX & Gaming Tech",          "Technology"),
    ("AU",     "After You Public Company Limited",       "Food & Desserts",            "mai"),
    ("SPA",    "Siam Wellness Group PCL",                "Spa & Hospitality",          "mai"),
    ("DOD",    "DOD Biotech Public Company Limited",     "Biotech & Supplements",      "mai"),
    ("FSMART", "Forth Smart Service PCL (Boonterm)",     "Fintech & Kiosk",            "mai"),
    ("ZIGA",   "Ziga Innovation Public Company Limited", "Industrial & Steel",         "mai"),
    ("NEX",    "Nex Point Public Company Limited",       "EV & Mobility",              "mai"),
]

def build_catalog():
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    
    stocks = []
    seen = set()
    for tk, nm, sec, ind in THAI_COMPANIES:
        if tk in seen:
            continue
        seen.add(tk)
        stocks.append({
            "ticker": tk,
            "symbol": f"{tk}.BK",
            "name": nm,
            "market": "SET",
            "sector": sec,
            "industry": ind,
            "currency": "THB"
        })
    
    payload = {
        "last_updated": datetime.now().isoformat(),
        "source": "Stock Exchange of Thailand (SET / mai) Master Catalog",
        "total": len(stocks),
        "stocks": stocks
    }
    
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
        
    print(f"✓ Saved {len(stocks)} Thai companies to {OUTPUT_FILE}")

if __name__ == "__main__":
    build_catalog()
